# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f390594133b42936134f0fead0d28d9bac3d4f0977176b960eb2d7beee099c7db3657e725c2c77c406b997e871a38c553be4396b69b3fd4ece04c5421ce29e

test:
  secret_key_base: 38442724756c4d44e8fac4307747c996b78742b753c67801eb7ca912db01b91ee6f17871bb4aaa247698e5e400ee744eb9022a9d5cd28b5b76946432616642ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
